export type GameCategory =
  | "kelime"
  | "sayı"
  | "mantık"
  | "hafıza"
  | "refleks"
  | "strateji";

export type GameMode = "single" | "multi";

export interface GameMeta {
  slug: string;
  name: string;
  short: string;
  howTo: string[];
  category: GameCategory;
  mode: GameMode;
  icon: string;
  hue: number; // accent hue for the card (0-360)
  scoreLabel: string;
  difficulty: 1 | 2 | 3;
}

export const CATEGORY_LABELS: Record<GameCategory, string> = {
  kelime: "Kelime",
  sayı: "Sayı",
  mantık: "Mantık",
  hafıza: "Hafıza",
  refleks: "Refleks",
  strateji: "Strateji",
};

export const GAMES: GameMeta[] = [
  // ---------- TEK KİŞİLİK (20) ----------
  {
    slug: "sudoku",
    name: "Sudoku",
    short: "Klasik 9x9 sayı yerleştirme bulmacası.",
    howTo: [
      "Her satır, sütun ve 3x3 kutuda 1-9 rakamları birer kez bulunmalı.",
      "Bir hücreye dokunup alttaki rakamlardan seç.",
      "Hatalı rakamlar kırmızı görünür; 3 hata hakkın var.",
      "Ne kadar hızlı ve hatasız bitirirsen o kadar çok puan!",
    ],
    category: "sayı",
    mode: "single",
    icon: "🔢",
    hue: 262,
    scoreLabel: "puan",
    difficulty: 3,
  },
  {
    slug: "2048",
    name: "2048",
    short: "Karoları kaydır, sayıları birleştir, 2048'e ulaş!",
    howTo: [
      "Ok tuşları veya kaydırma hareketiyle tüm karoları bir yöne it.",
      "Aynı sayılar çarpışınca birleşip iki katına çıkar.",
      "Hedef: 2048 karosunu oluşturmak. Tahta dolarsa oyun biter.",
    ],
    category: "sayı",
    mode: "single",
    icon: "🧮",
    hue: 35,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "mayin-tarlasi",
    name: "Mayın Tarlası",
    short: "Mayınlara basmadan tüm güvenli kareleri aç.",
    howTo: [
      "Bir kareye dokunarak aç; sayılar komşu mayın sayısını gösterir.",
      "Bayrak modunu açıp mayın olduğunu düşündüğün karelere bayrak koy.",
      "Tüm güvenli kareleri açarsan kazanırsın.",
    ],
    category: "mantık",
    mode: "single",
    icon: "💣",
    hue: 0,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "hafiza-kartlari",
    name: "Hafıza Kartları",
    short: "Kart çiftlerini en az hamlede eşleştir.",
    howTo: [
      "İki kart çevir; aynıysa açık kalır, değilse kapanır.",
      "Kartların yerlerini aklında tut.",
      "Tüm çiftleri en az hamlede ve en hızlı şekilde bul.",
    ],
    category: "hafıza",
    mode: "single",
    icon: "🃏",
    hue: 200,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "kayan-bulmaca",
    name: "Kayan Bulmaca",
    short: "Karoları kaydırarak 1'den 15'e sırala.",
    howTo: [
      "Boş kareye komşu karolara dokunarak kaydır.",
      "Sayıları soldan sağa, yukarıdan aşağı sırala.",
      "Daha az hamle = daha çok puan.",
    ],
    category: "mantık",
    mode: "single",
    icon: "🧩",
    hue: 160,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "kelime-avi",
    name: "Kelime Avı",
    short: "Harf ızgarasında gizlenen kelimeleri bul.",
    howTo: [
      "Listedeki kelimeler ızgarada yatay, dikey veya çapraz gizli.",
      "Kelimenin ilk harfine basılı tutup son harfe sürükle.",
      "Tüm kelimeleri bulunca oyun biter; hız puan kazandırır.",
    ],
    category: "kelime",
    mode: "single",
    icon: "🔍",
    hue: 290,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "adam-asmaca",
    name: "Adam Asmaca",
    short: "Kelimeyi harf harf tahmin et, adamı kurtar!",
    howTo: [
      "Gizli kelimeyi bulmak için harf seç.",
      "Her yanlış harf adamı biraz daha asar; 6 hata hakkın var.",
      "Arka arkaya kelimeler çözerek seri yap, puan topla.",
    ],
    category: "kelime",
    mode: "single",
    icon: "🪢",
    hue: 20,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "kelimle",
    name: "Kelimle",
    short: "5 harfli gizli kelimeyi 6 denemede bul.",
    howTo: [
      "5 harfli bir kelime yaz ve onayla.",
      "Yeşil: harf doğru yerde. Sarı: kelimede var ama yanlış yerde. Gri: kelimede yok.",
      "6 denemede kelimeyi bulmaya çalış; az denemede bulmak daha çok puan.",
    ],
    category: "kelime",
    mode: "single",
    icon: "🟩",
    hue: 140,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "simon",
    name: "Simon Der Ki",
    short: "Renk dizisini izle ve aynı sırayla tekrarla.",
    howTo: [
      "Renkler sırayla yanar; diziyi aklında tut.",
      "Aynı sırayla renklere dokun.",
      "Her turda dizi bir uzar. Kaç tura dayanabilirsin?",
    ],
    category: "hafıza",
    mode: "single",
    icon: "🚦",
    hue: 330,
    scoreLabel: "seviye",
    difficulty: 1,
  },
  {
    slug: "nonogram",
    name: "Nonogram",
    short: "Sayı ipuçlarıyla gizli resmi ortaya çıkar.",
    howTo: [
      "Satır ve sütunlardaki sayılar, o hattaki dolu blokların uzunluğunu sırayla gösterir.",
      "Dolu olduğunu düşündüğün kareleri boya, boş olanları X ile işaretle.",
      "Tüm ızgarayı doğru çözersen resim ortaya çıkar.",
    ],
    category: "mantık",
    mode: "single",
    icon: "🖼️",
    hue: 220,
    scoreLabel: "puan",
    difficulty: 3,
  },
  {
    slug: "isiklari-kapat",
    name: "Işıkları Kapat",
    short: "Tüm ışıkları söndür — ama her dokunuş komşuları da değiştirir!",
    howTo: [
      "Bir kareye dokununca kendisi ve 4 komşusu tersine döner.",
      "Amaç tüm ışıkları söndürmek.",
      "Ne kadar az hamle, o kadar çok puan.",
    ],
    category: "mantık",
    mode: "single",
    icon: "💡",
    hue: 50,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "hanoi",
    name: "Hanoi Kulesi",
    short: "Diskleri en az hamleyle diğer çubuğa taşı.",
    howTo: [
      "Tüm diskleri en sağdaki çubuğa taşı.",
      "Tek seferde bir disk taşınır ve büyük disk küçüğün üstüne konamaz.",
      "Minimum hamle sayısına yaklaştıkça puanın artar.",
    ],
    category: "mantık",
    mode: "single",
    icon: "🗼",
    hue: 180,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "matematik-kosusu",
    name: "Matematik Koşusu",
    short: "60 saniyede olabildiğince çok işlem çöz.",
    howTo: [
      "Ekrandaki işlemin sonucunu seçeneklerden bul.",
      "Doğru cevap +1 puan ve ekstra süre, yanlış cevap süre kaybettirir.",
      "Süre bitmeden en yüksek skoru yap!",
    ],
    category: "sayı",
    mode: "single",
    icon: "➕",
    hue: 210,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "anagram",
    name: "Anagram Avı",
    short: "Karışık harflerden gizli kelimeyi çöz.",
    howTo: [
      "Harfleri doğru sıraya dizerek kelimeyi bul.",
      "Harflere dokunarak kelimeyi oluştur.",
      "Süre bitmeden olabildiğince çok kelime çöz; ipucu kullanmak puan düşürür.",
    ],
    category: "kelime",
    mode: "single",
    icon: "🔤",
    hue: 310,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "sifre-kirici",
    name: "Şifre Kırıcı",
    short: "Gizli renk kodunu mantıkla çöz (Mastermind).",
    howTo: [
      "4 renkten oluşan gizli kodu 10 denemede bul.",
      "Her denemede ipucu alırsın: tam isabet ve yanlış yerdeki doğru renk sayısı.",
      "Az denemede çözmek daha çok puan kazandırır.",
    ],
    category: "mantık",
    mode: "single",
    icon: "🕵️",
    hue: 250,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "yilan",
    name: "Yılan",
    short: "Klasik yılan: ye, büyü, duvara çarpma!",
    howTo: [
      "Ok tuşları veya ekrandaki yön butonlarıyla yılanı yönlendir.",
      "Elmaları yedikçe büyür ve hızlanırsın.",
      "Duvara veya kendine çarparsan oyun biter.",
    ],
    category: "refleks",
    mode: "single",
    icon: "🐍",
    hue: 120,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "renk-tuzagi",
    name: "Renk Tuzağı",
    short: "Yazıya değil renge odaklan! (Stroop testi)",
    howTo: [
      "Ekranda bir renk ismi, farklı bir renkte yazılmış olabilir.",
      "Kelimenin ANLAMINA değil, YAZI RENGİNE göre cevap ver.",
      "60 saniyede olabildiğince çok doğru cevap ver.",
    ],
    category: "refleks",
    mode: "single",
    icon: "🎨",
    hue: 15,
    scoreLabel: "puan",
    difficulty: 1,
  },
  {
    slug: "sayi-hafizasi",
    name: "Sayı Hafızası",
    short: "Sayıyı gör, ezberle, yaz. Her tur bir hane uzar!",
    howTo: [
      "Ekranda beliren sayıyı aklında tut.",
      "Sayı kaybolunca hatırladığını yaz.",
      "Her doğru cevapta sayı bir basamak uzar. Hafızan kaç haneye dayanır?",
    ],
    category: "hafıza",
    mode: "single",
    icon: "🧠",
    hue: 270,
    scoreLabel: "basamak",
    difficulty: 1,
  },
  {
    slug: "tek-kal",
    name: "Tek Kal",
    short: "Taşları üstünden atlayarak ele; tahtada tek taş bırak.",
    howTo: [
      "Bir taşı seçip yanındaki taşın üzerinden boş kareye atlat.",
      "Üzerinden atlanan taş tahtadan kalkar.",
      "Amaç tahtada tek taş bırakmak. Ne kadar az taş kalırsa o kadar iyi!",
    ],
    category: "mantık",
    mode: "single",
    icon: "📍",
    hue: 90,
    scoreLabel: "puan",
    difficulty: 3,
  },
  {
    slug: "refleks-testi",
    name: "Refleks Testi",
    short: "Yeşili görünce en hızlı sen dokun!",
    howTo: [
      "Ekran kırmızıyken bekle. Yeşile dönünce hemen dokun!",
      "Erken dokunursan tur yanar.",
      "5 turun ortalaması skorun olur; düşük milisaniye = yüksek puan.",
    ],
    category: "refleks",
    mode: "single",
    icon: "⚡",
    hue: 55,
    scoreLabel: "puan",
    difficulty: 1,
  },

  // ---------- ÇOK OYUNCULU (10) ----------
  {
    slug: "xox",
    name: "XOX",
    short: "Klasik üç taş: sırayla işaret koy, üçlü yap.",
    howTo: [
      "Sırayla boş karelere işaretini koy.",
      "Yatay, dikey veya çapraz üçlü yapan kazanır.",
      "Aynı cihazda veya online oda kurarak oyna.",
    ],
    category: "strateji",
    mode: "multi",
    icon: "❌",
    hue: 340,
    scoreLabel: "galibiyet",
    difficulty: 1,
  },
  {
    slug: "dortlu-dizi",
    name: "Dörtlü Dizi",
    short: "Pulları bırak, rakipten önce 4'lü diz!",
    howTo: [
      "Sırayla bir sütuna pul bırak; pul en alta düşer.",
      "Yatay, dikey veya çapraz 4 pul dizen kazanır.",
      "Rakibin dizisini engellemeyi unutma!",
    ],
    category: "strateji",
    mode: "multi",
    icon: "🔴",
    hue: 220,
    scoreLabel: "galibiyet",
    difficulty: 1,
  },
  {
    slug: "nokta-kutu",
    name: "Noktalar ve Kutular",
    short: "Çizgileri çiz, kutuları kap!",
    howTo: [
      "Sırayla iki komşu nokta arasına çizgi çiz.",
      "Bir kutunun 4. kenarını çizen kutuyu alır ve bir hamle daha yapar.",
      "En çok kutuyu toplayan kazanır.",
    ],
    category: "strateji",
    mode: "multi",
    icon: "📦",
    hue: 190,
    scoreLabel: "kutu",
    difficulty: 2,
  },
  {
    slug: "amiral-batti",
    name: "Amiral Battı",
    short: "Rakibin gemilerini bul ve batır!",
    howTo: [
      "Gemilerini yerleştir (karıştır butonuyla dizilimi değiştirebilirsin).",
      "Sırayla rakibin denizine atış yap: isabet 🔥, ıska 💧.",
      "Tüm rakip gemilerini ilk batıran kazanır.",
    ],
    category: "strateji",
    mode: "multi",
    icon: "🚢",
    hue: 205,
    scoreLabel: "galibiyet",
    difficulty: 2,
  },
  {
    slug: "reversi",
    name: "Reversi",
    short: "Rakip taşları çevir, tahtayı ele geçir!",
    howTo: [
      "Taşını, rakip taşları iki taşın arasına alacak şekilde koy.",
      "Arada kalan tüm rakip taşlar senin rengine döner.",
      "Tahta dolunca en çok taşı olan kazanır.",
    ],
    category: "strateji",
    mode: "multi",
    icon: "⚫",
    hue: 150,
    scoreLabel: "taş",
    difficulty: 2,
  },
  {
    slug: "dama",
    name: "Dama",
    short: "Çapraz ilerle, rakip taşları atla ve topla.",
    howTo: [
      "Taşlar çapraz ilerler; rakip taşın üzerinden atlayarak onu alırsın.",
      "Alma hamlesi varsa yapmak zorundasın; zincirleme atlama yapılabilir.",
      "Son sıraya ulaşan taş dama (kral) olur ve geriye de gidebilir.",
    ],
    category: "strateji",
    mode: "multi",
    icon: "🏁",
    hue: 10,
    scoreLabel: "galibiyet",
    difficulty: 3,
  },
  {
    slug: "kelime-duellosu",
    name: "Kelime Düellosu",
    short: "Aynı harflerden sırayla kelime türet, rakibini pas geçir!",
    howTo: [
      "Ortadaki harf havuzundan sırayla kelime üret (en az 3 harf).",
      "Her harf puan getirir; uzun kelime daha çok kazandırır.",
      "Kelime bulamayan pas geçer; üst üste iki pas oyunu bitirir. Yüksek puan kazanır.",
    ],
    category: "kelime",
    mode: "multi",
    icon: "⚔️",
    hue: 300,
    scoreLabel: "puan",
    difficulty: 2,
  },
  {
    slug: "hafiza-duellosu",
    name: "Hafıza Düellosu",
    short: "Eşleşen kartı bulan devam eder — en çok çifti topla!",
    howTo: [
      "Sırayla iki kart aç.",
      "Eşleştirirsen çifti alırsın ve sıra sende kalır.",
      "Kartlar bitince en çok çifti toplayan kazanır.",
    ],
    category: "hafıza",
    mode: "multi",
    icon: "🎴",
    hue: 170,
    scoreLabel: "çift",
    difficulty: 1,
  },
  {
    slug: "nim",
    name: "Nim Taşları",
    short: "Sırayla taş al; son taşı alan kazanır!",
    howTo: [
      "Sırayla tek bir sıradan istediğin kadar taş al.",
      "Son taşı alan oyunu kazanır.",
      "Matematiksel strateji ile rakibini köşeye sıkıştır!",
    ],
    category: "strateji",
    mode: "multi",
    icon: "🪨",
    hue: 30,
    scoreLabel: "galibiyet",
    difficulty: 2,
  },
  {
    slug: "bes-tas",
    name: "Beş Taş",
    short: "15x15 tahtada rakipten önce 5'li diz (Gomoku).",
    howTo: [
      "Sırayla boş bir kesişime taş koy.",
      "Yatay, dikey veya çapraz kesintisiz 5 taş dizen kazanır.",
      "Hem saldır hem savun — 4'lüleri asla görmezden gelme!",
    ],
    category: "strateji",
    mode: "multi",
    icon: "⭕",
    hue: 260,
    scoreLabel: "galibiyet",
    difficulty: 2,
  },
];

export const GAME_MAP: Record<string, GameMeta> = Object.fromEntries(
  GAMES.map((g) => [g.slug, g])
);

export const SINGLE_GAMES = GAMES.filter((g) => g.mode === "single");
export const MULTI_GAMES = GAMES.filter((g) => g.mode === "multi");
